services:
  backend:
    build: ./backend
    container_name: herbal_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/herbal_cosmetics_db
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app/uploads:/app/app/uploads
    restart: unless-stopped

  frontend:
    build: .
    container_name: herbal_frontend
    environment:
      - VITE_API_URL=/api/v1
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: herbal_cosmetics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d herbal_cosmetics_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

