version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: herbal_cosmetics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/herbal_cosmetics_db
    volumes:
      - ./app/uploads:/app/app/uploads

volumes:
  postgres_data:

